#!/usr/bin/env python2
# Copyright (c) 2014-2016, NVIDIA CORPORATION.  All rights reserved.

import argparse
import sys

import digits

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Run the DIGITS development server')
    parser.add_argument('-p', '--port',
            type=int,
            default=5000,
            help='Port to run app on (default 5000)'
            )
    parser.add_argument('-c', '--config',
            action='store_true',
            help='Edit the application configuration'
            )
    parser.add_argument('-d', '--debug',
            action='store_true',
            help='Run the application in debug mode (reloads when the source changes and gives more detailed error messages)'
            )
    parser.add_argument('--version',
            action='store_true',
            help='Print the version number and exit'
            )

    args = vars(parser.parse_args())

    from digits import config

    if args['version']:
        print digits.__version__
        sys.exit()

    if args['config']:
        config.load_config('normal')
    else:
        config.load_config('quiet')

    from digits.webapp import app, socketio, scheduler

    print '  ___ ___ ___ ___ _____ ___'
    print ' |   \_ _/ __|_ _|_   _/ __|'
    print ' | |) | | (_ || |  | | \__ \\'
    print ' |___/___\___|___| |_| |___/', digits.__version__
    print

    try:
        if not scheduler.start():
            print 'ERROR: Scheduler would not start'
        else:
            app.debug = args['debug']
            socketio.run(app, '0.0.0.0', args['port'])
    except KeyboardInterrupt:
        pass
    finally:
        scheduler.stop()

