#!/bin/bash
# Copyright (c) 2014-2015, NVIDIA CORPORATION.  All rights reserved.

# set level
if [ -z "$DIGITS_LEVEL" ]
then
    DIGITS_LEVEL=system
fi

DIGITS_LEVEL=$DIGITS_LEVEL gunicorn --config gunicorn_config.py digits.webapp:app
