#!/bin/bash
# Copyright (c) 2014-2017, NVIDIA CORPORATION.  All rights reserved.

set -e

function set_exe {
    # Sets a global variable to the location of an executable
    # Arguments:
    # $1 -- the variable name
    # $2 -- the executable

    # Check to make sure the executable exists
    hash $2 2>/dev/null || { echo >&2 "ERROR: \"$2\" executable not found!"; exit 1; }
    # Print the path to the executable
    local __resultvar=$1
    eval $__resultvar="'$(command -v $2)'"
}

# Some hacking necessary to respect virtualenv installations
set_exe PYTHON_EXE python2
set_exe NOSE_EXE nosetests

DIGITS_MODE_TEST=1 $PYTHON_EXE $NOSE_EXE \
    --no-path-adjustment $@
